name: Deploy to Amazon ECS

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: ap-southeast-1                     # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: iisc_capstone_group6           # set this to your Amazon ECR repository name
  ECS_SERVICE: ecs_task_for_capstonegroup6_LB                 # set this to your Amazon ECS service name
  ECS_CLUSTER: iisc_capstone_group6_cluster                 # set this to your Amazon ECS cluster name
  ECS_TASK_DEFINITION: sample_fargate.json # set this to the path to your Amazon ECS task definition
                                               # file, e.g. .aws/task-definition.json
  CONTAINER_NAME: finsmart set this to the name of the container in the
                                               # containerDefinitions section of your task definition

permissions:
  contents: read

jobs:
  bert_build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: Install dependencies
      working-directory: ./models/finbert
      run: |
        pip install --upgrade build
        pip install -r requirements.txt
    - name: Build package
      working-directory: ./models/finbert
      run: python -m build
    - uses: actions/upload-artifact@v3
      with:
        name: finsenti-package
        path: models/finbert/dist/*.whl
        
  data_build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Install dependencies
        working-directory: ./findata/
        run: |
          pip install --upgrade build
          pip install -r requirements.txt
      - name: Build package
        working-directory: ./findata/
        run: python -m build
      - uses: actions/upload-artifact@v3
        with:
          name: findata-package
          path: findata/dist/*.whl
