name: FIN SMART CI Pipeline
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  bert_build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        pip install wheel
        pip install -r models/finbert/requirements.txt
    - name: Build package
      run: python models/finbert/setup.py bdist_wheel
    - uses: actions/upload-artifact@v2
      with:
        name: finsenti-package
        path: dist/*.whl

  data_build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install wheel
          pip install -r findata/requirements.txt
      - name: Build package
        run: python findata/setup.py bdist_wheel
      - uses: actions/upload-artifact@v2
        with:
          name: findata-package
          path: dist/*.whl

  docker_build:
    needs: ["data_build", "bert_build"]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - uses: actions/download-artifact@v2
        with:
          name: findata-package
      - run: mv *.whl api/

      - uses: actions/download-artifact@v2
        with:
          name: finsenti-package
      - run: mv *.whl api/

      - name: Login to Docker hub
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN}}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Build the Docker image for Fastapi app
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
        run: docker build . -f Dockerfile -t $DOCKER_USER/finsmart:latest

      - name: Push the Docker Image
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
        run: docker push $DOCKER_USER/finsmart

      - name: Logout to Docker hub
        run: docker logout